### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by RobLeachman** [EVE-Tools/element43#38]
Initial install seemed to go fine but no joy at the very end, no price data to DB as near as I can tell. Maybe this will help explain:

http://pastebin.com/a7hbcrge

I wanted clean logs and such so I restarted the VM and now I can't figure out how to connect with supervisorctl at all. Do I need to source into a virtualenv or something? Lost.

gtaylor said you've got finals, good luck with those and THANKS

**Comment by zweizeichen** [comment]
Thank you for filing your issue - I'll help you - just give me two weeks :)

**Comment by zweizeichen** [comment]
Sorry that it took me a little longer than I expected. First, there seem to be some networking-related issues on your VM. Could you try to reboot the machine and check that its connection to the internet is working as intended? Second, it looks like the import of the SDE failed - try to re-run the provisioning script.
