### ISSUE TITLE
Evaluate migrating to hosted CI

### ISSUE THREAD

**Issue by zweizeichen** [EVE-Tools/element43#54]
While running our own CI system can be fun, it is yet another service to maintain. We could migrate to one of the numerous CI platforms which offer free services for open-source projects.

**Comment by gtaylor** [comment]
Circle was pretty good in the past, though I'm out of date by a couple years.

**Comment by zweizeichen** [comment]
Just ran some quick test builds of [esi-markets](https://github.com/EVE-Tools/esi-markets) as Rust takes a while to compile. Each service was executing the same Dockerfile. So here's the comparison of build times for Travis CI vs. Circle CI vs. Semaphore CI:

| Service  | Build Times | Comment |
| --- | --- | --- |
| Travis CI | 10m14s, 10m54s, 9m26s | Good old Travis CI. Ran some unnecessary setup for the language toolchain which is not needed for simply building a Docker image. |
| Semaphore CI | 3m39s, 4m30s, 4m29s | Painless setup using their wizard, no fiddling with config files in the repo which I always get wrong on the first try. It even asked for Docker Hub integration for pushing the image. |
| Circle CI | 8m33s | Not the fastest even if specs looked promising. Lots of features, felt a little 'enterprisey'. |

Of course there are more things to consider than raw speed when picking a hosted CI solution. Semaphore CI blew the others out of the water performance-wise (may be related to using RAM-disks). Also, I liked their UX and they've got [v2](https://semaphoreci.com/v2-is-coming) coming up which promises improved Kubernetes support. It should serve our needs well. So I'm picking Semaphore CI for the time being.

**Comment by zweizeichen** [comment]
Closing as all relevant services (esi-markets, top-stations and market-stats) have been ported to Semaphore CI, with the exception of:

- vue43 - it'll get a major overhaul soonish, removing nuxt and server-side rendering which cost more effort to maintain than it was worth, also the backend is going to move to GraphQL
- static-data is going to be replaced by the much cleaner GraphQL gateway
- jumpgate - can be 'revived' at a later point in time if e.g. users want a REST-ish API
- market-streamer - an old build is still available however I don't think anyone is using it
